package art

import "image"

// Anim is a named animation strip. All frames share the same size.
// Frames face right; the game mirrors them with FlipH (or a negative
// GeoM scale) when facing left.
type Anim struct {
	Name   string
	Frames []*image.RGBA
	FPS    float64
	Loop   bool
}

func (a Anim) Size() (int, int) {
	b := a.Frames[0].Bounds()
	return b.Dx(), b.Dy()
}

// ---------------------------------------------------------------- Jack ----

const jackHead = `
....K.....K.....
...KbK...KbK....
...KbbKKKbbK....
...KbbbbbbbbK...
...KbWKbbWKbK...
...KbSSSSSSSK...
....KSSSSrSK....
`

func jack(rows string) *image.RGBA { return sprite16(jackHead + rows) }

func jackIdle() []*image.RGBA {
	return []*image.RGBA{
		jack(`
			.....KKKKKK.....
			..RRKBBBBBBBK...
			.RRRKBBBBBBBK...
			.RRRKSYYYYYSK...
			.rRRKBBBBBBBK...
			.rrRKBBBKBBBK...
			..rrKBBK.KBBK...
			...KRRRK.KRRRK..
			...KKKKK.KKKKK..`),
		jack(`
			.....KKKKKK.....
			...RKBBBBBBBK...
			..RRKBBBBBBBK...
			.RRRKSYYYYYSK...
			RRRrKBBBBBBBK...
			rRr.KBBBKBBBK...
			r...KBBK.KBBK...
			...KRRRK.KRRRK..
			...KKKKK.KKKKK..`),
	}
}

const jackRunTop = `
.....KKKKKK.....
RRRRKBBBBBBBK...
.RRRKBBBBBBSK...
..rRKBYYYYYSK...
...rKBBBBBBBK...
`

func jackRun() []*image.RGBA {
	stride := jack(jackRunTop + `
		....KBBBBBBBK...
		...KBBBK.KBBBK..
		..KRRRK...KRRRK.
		..KKKKK...KKKKK.`)
	pass := jack(jackRunTop + `
		....KBBBBBBBK...
		....KBBBBBBK....
		.....KRRRRK.....
		.....KKKKKK.....`)
	kick := jack(jackRunTop + `
		....KBBBBBBBK...
		....KBBKKBBBK...
		...KRRRK.KRRRRK.
		...KKKKK..KKKKK.`)
	return []*image.RGBA{stride, pass, kick, pass}
}

func jackJump() []*image.RGBA {
	return []*image.RGBA{jack(`
		.KSK.KKKKKK.KSK.
		.KBKKBBBBBBKKBK.
		..KBBBBBBBBBBK..
		..RKBYYYYYYBKR..
		.RRKBBBBBBBBKRR.
		.RRKBBBBBBBBKRR.
		.rRRKBBKKBBKRRr.
		..rrKRRKKRRKrr..
		....KKKKKKKK....`)}
}

func jackFloat() []*image.RGBA {
	return []*image.RGBA{
		jack(`
			.....KKKKKK.....
			KKKKKBBBBBBKKKKK
			KSBBBBBBBBBBBBSK
			RKKKKBYYYYBKKKKR
			RRRRKBBBBBBKRRRR
			rRRRKBBBBBBKRRRr
			.rRRKBBKKBBKRRr.
			..rrKRRKKRRKrr..
			....KKKKKKKK....`),
		jack(`
			.....KKKKKK.....
			KKKKKBBBBBBKKKKK
			KSBBBBBBBBBBBBSK
			RKKKKBYYYYBKKKKR
			.RRRKBBBBBBKRRR.
			RRRRKBBBBBBKRRRR
			rRRrKBBKKBBKrRRr
			.rr.KRRKKRRK.rr.
			....KKKKKKKK....`),
	}
}

func jackDie() []*image.RGBA {
	base := jackIdle()[0]
	return []*image.RGBA{base, Rot90(base, 1), Rot90(base, 2), Rot90(base, 3)}
}

// ------------------------------------------------------------- enemies ----

const mummyTop = `
................
.....KKKKK......
....KTTTTTK.....
....KtTtTTK.....
....KTTRTRK.....
....KtTTTtK.....
.....KTtTK......
....KTTTtTKKKKK.
...KTtTTTTTTTTTK
...KTTtTTKKKKK..
...KtTTTTK......
...KTTtTTK......
...KTtTTtK......
`

func mummyWalk() []*image.RGBA {
	a := sprite16(mummyTop + `
		...KTTKTTK......
		..KTTK.KTTK.....
		..KKKK..KKKK....`)
	b := sprite16(mummyTop + `
		....KTTTK.......
		....KTTK........
		....KKKKK.......`)
	return []*image.RGBA{a, b}
}

func birdFly() []*image.RGBA {
	up := sprite16(`
		................
		.K..........K...
		.KPK.......KPK..
		..KPK.....KPPK..
		..KPPK...KPPK...
		...KPPK.KPPK....
		....KPPKPPKKKK..
		....KPPPPPKWWK..
		...KpPPPPPPKKOOK
		..KppPPPPPPPKKK.
		.KpKKpPPPPPK....
		.KK..KKKKKK.....`)
	mid := sprite16(`
		................
		................
		................
		................
		................
		................
		..........KKKK..
		KKKK.KKKKKKWWK..
		KPPPKpPPPPPKKOOK
		.KPPPpPPPPPPKKK.
		..KKKKPPPPPK....
		......KKKKK.....`)
	down := sprite16(`
		................
		................
		................
		................
		................
		................
		..........KKKK..
		....KKKKKKKWWK..
		...KpPPPPPPKKOOK
		..KppPPPPPPPKKK.
		.KpKPPPPPPPK....
		.KK.KPPKPPK.....
		....KPPKKPPK....
		...KPPK..KPPK...
		...KPK....KPK...
		...KK......KK...`)
	return []*image.RGBA{up, mid, down, mid}
}

func saucerSpin() []*image.RGBA {
	top := `
		................
		................
		................
		................
		......KKKK......
		.....KCWCCK.....
		....KCCCCcCK....
		..KKKKKKKKKKKK..
		.KwwwwwwwwwwwwK.
	`
	bottom := `
		.KgggggggggggggK
		..KKKKKKKKKKKKK.
		....KK....KK....
	`
	lights := []string{
		"KGYGGGRGGGYGGGRK",
		"KGGYGGGRGGGYGGGK",
		"KGGGRGGGYGGGRGGK",
		"KRGGGYGGGRGGGYGK",
	}
	var out []*image.RGBA
	for _, l := range lights {
		out = append(out, sprite16(top+l+bottom))
	}
	return out
}
